
---
title: "Countertop Salinity Investigation"
output:
 html_document:
    df_print: paged
    code_folding: hide
    toc: TRUE
    toc_depth: 4
    toc_float: true
    theme: cerulean
    highlight: haddock
    smart: false
editor_options: 
  chunk_output_type: inline
---


Hello World

Author: OA Lab, NWFSC
Title: Salmon Shed Tanks
Date: 2018-2019 (R document January-April 2021)

CRB_JUVambientsalmonshedconditions(2018-2019)TempMasterFile(2021.03.31)


# Version Check
```{r 0.1 Version Check , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
## Version Check
#********************************* 
R.version

```



# Libraries
```{r 0.0 Libraries , echo=FALSE, results=FALSE, message=FALSE, warning=FALSE}
#*********************************
##Libraries
#********************************* 
library(here)
library(stringr)
library(data.table)
library(tidyverse)
library(plyr)
library(nlme)
library(tidyr)
library(dbplyr)
library(dplyr)
library(purrr)
library(wql)
library(lubridate)
library(tibbletime)
library(arsenal)
library(compareDF)
library(metacsv)
#for graphing
library(ggplot2)
library(ggfortify)
library(stringr)
library(nlme)
library(RColorBrewer)
library(patchwork)
#statistical analysis
library(gdata)
library(rsq)
library(doBy)
#Rnotebooks 
library(gridExtra)
library(kableExtra)

```



# 1.) Setting Working Directory
```{r 1.) Setting Working Directory, echo=FALSE, results=FALSE, message=FALSE, warning=FALSE }
#*********************************
## 1.) Setting Working Directory
#*********************************

#set working directory to the correct folder
# setwd("/Users/katherinerovinski/GIT/NWFSC.MUK_DGNjuvenile.tanks/01_rawData")


```



# 2.) Creating the Dataframe
```{r 2.) Creating the Dataframe, echo=FALSE, message=FALSE, warning=FALSE}

#*********************************
## 2.) Creating the initial Dataframes
#*********************************


#set working directory to the correct folder
temp_Log <- read_csv(here::here("02_processedData",
                          "MasterTimeSeries","2021.03.31_Master_Temperature_log.csv"))

temp_pH <- read_csv(here::here("02_processedData",
                               "MasterTimeSeries","2021.03.31_pH_timeseries_log.csv"))

temp_salinty <- read_csv(here::here("02_processedData",
                                    "MasterTimeSeries","2021.03.31_salinity_timeseries_log.csv"))

```




```{r}
#################################
# END OF SCRIPT | END OF DOCUMENT
#################################
```

#################################
# END OF SCRIPT | END OF DOCUMENT
#################################
























